name: flutter_bloc_demo
description: A new flutter module project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #第一步 引入Rxdart
  rxdart: ^0.19.0

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  module:
    androidPackage: com.example.flutter_bloc_demo
    iosBundleIdentifier: com.example.flutterBlocDemo
